import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
    ],
  },
  theme: {
    mytheme: {
      "primary": "#7c3aed",
      "primary-content": "#e1dbff",
      "secondary": "#c026d3",
      "secondary-content": "#f5d9f8",
      "accent": "#00ffff",
      "accent-content": "#001616",
      "neutral": "#c084fc",
      "neutral-content": "#0e0616",
      "base-100": "#f3e8ff",
      "base-200": "#d3cade",
      "base-300": "#b4acbe",
      "base-content": "#141316",
      "info": "#0000ff",
      "info-content": "#c6dbff",
      "success": "#00ff00",
      "success-content": "#001600",
      "warning": "#00ff00",
      "warning-content": "#001600",
      "error": "#ff0000",
      "error-content": "#160000",
    },
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
      },
    },
  },
  plugins: [require('daisyui')],
};
export default config;